name: Code Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # 👈 Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Linters
        run: |
          npm install -g eslint stylelint stylelint-config-standard

      - name: Run ESLint (JavaScript)
        run: eslint "**/*.js" --max-warnings=0

      - name: Run Stylelint (CSS)
        run: stylelint "**/*.css" --max-warnings=0

      - name: Validate HTML with W3C
        run: |
          for file in $(find . -name "*.html"); do
            curl -s --data-binary @"$file" -H "Content-Type: text/html" "https://validator.w3.org/nu/?out=json" | jq '.messages[] | select(.type=="error")' > errors.json
            if [ -s errors.json ]; then cat errors.json; exit 1; fi
          done
