name: Code Validation & Linting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # 👈 Allows manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Linters
        run: |
          npm install -g eslint stylelint

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Run ESLint on changed JS files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          eslint $(git diff --name-only HEAD^ HEAD | grep '\.js$' || true)

      - name: Run Stylelint on changed CSS files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          stylelint $(git diff --name-only HEAD^ HEAD | grep '\.css$' || true)

      - name: Validate HTML on changed HTML files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in $(git diff --name-only HEAD^ HEAD | grep '\.html$' || true); do
            curl -s --data-binary @"$file" -H "Content-Type: text/html" "https://validator.w3.org/nu/?out=json"
          done
